language: go

os: linux

dist: bionic

go:
  - '1.13.x'

services:
  - docker

env:
  global:
    - GO111MODULE=on
    - KIND_VERSION=v0.7.0
    - OPERATOR_SDK_VERSION=v0.16.0
    - IMAGE_NAME=quay.io/mittwald/kubernetes-secret-generator
    - KUBECONFIG="/tmp/kubeconfig"

.before_build: &before_build |-
  curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu && chmod +x operator-sdk && sudo mv operator-sdk /usr/local/bin

before_deploy:
  - docker login -u "${DOCKER_LOGIN_USERNAME}" -p "${DOCKER_LOGIN_PASSWORD}" quay.io

jobs:
  include:
    - stage: test
      install:
        - curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
        - kind get kubeconfig --internal --name kind-${CI_CONCURRENT_ID} | tee ${KUBECONFIG}
      script:
        - make test
      name: "test"

    - script:
        - diff -u <(echo -n) <(gofmt -d -s .)
      name: "gofmt"

    - stage: build
      before_script:
        - *before_build
      script:
        - make build DOCKER_IMAGE="${IMAGE_NAME}:latest" KUBE_SECRET_OPERATOR_VERSION=${TRAVIS_COMMIT::8}

    - stage: deploy
      before_script:
        - *before_build
      script:
        - make build DOCKER_IMAGE="${IMAGE_NAME}:latest" KUBE_SECRET_OPERATOR_VERSION=${TRAVIS_COMMIT::8}
        - docker push "${IMAGE_NAME}:latest"
      if: (branch = master) AND (tag IS blank)

    - stage: deploy
      before_script:
        - *before_build
      script:
        - make build DOCKER_IMAGE="${IMAGE_NAME}:latest" KUBE_SECRET_OPERATOR_VERSION=${TRAVIS_TAG}
        - docker tag "${IMAGE_NAME}:latest" "${IMAGE_NAME}:${TRAVIS_TAG}"
        - docker push "${IMAGE_NAME}:latest"
        - docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
        - bash ./scripts/bump-app-version.sh publish
      if: (branch = master) AND (tag IS present)
